name: CDGitops

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write   # required for pushing the kustomize update back to the repo

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and push to Dockerhub
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/golang-argo
        tags: ${{ github.sha }}, latest

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize_version: "3.6.1"

    - name: Update Kubernetes Resources
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        cd k8s
        kustomize edit set image goserver=$DOCKER_USERNAME/golang-argo:$GITHUB_SHA

    - name: Commit
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git commit -am "Apply kustomization"
      
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: FranciscoGSilverio/argocd-minimal-example